title:            consolacao
description:      Harald Haesler
disqus_shortname: 
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://consolacao.github.io

# Owner/author information
owner:
  name:           Harald Haesler
  avatar:         avatar.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
  email:          github@werkkreis.org
  # Social networking links used in footer. Update and remove as you like.
  twitter:        https://twitter.com/consolacao2
  facebook:       https://www.facebook.com/Harald.Haesler?ref=profile
  github:         https://www.facebook.com/Harald.Haesler?ref=profile
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:        http://www.tumblr.com/blog/haesler 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/105817282553018339451?rel=author

# Background image to be tiled on all pages
background: witewall_3.png

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Lageplan
    url: /theme-setup
  - title: Aktuelle Baustelle
    url: http://www.tajine.de/RELAUNCH
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Germany/Munich
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]