source 'https://rubygems.org'

gem 'jekyll'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'coveralls', require: false
gem 'json'
gem 'jekyll-mentions'
gem 'jemoji'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'glynn'
gem 'redcarpet', '~> 2.3'
gem 'albino', '~> 1.3'
gem 'twitter', '~> 5.9.0'
gem 'omniauth', '~> 1.2.1'